In [2]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# taking square root of every value in the array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
#exponential of every value in the array
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
#Binary functions- requires 2 arrays
#random - random numbers, randn - random normal distribution  **will be covered later in course

A = np.random.randn(10)
A

array([-1.08404305, -0.59171913,  1.15249635, -0.46612771, -0.35773992,
       -0.06643579, -1.19992588,  2.27022593, -1.79028709,  0.04067564])

In [6]:
B = np.random.randn(10)
B

array([-0.32942746,  0.35523941, -0.16657507, -0.86143447, -0.80815738,
       -0.04604959,  0.09227759,  1.6456672 , -0.95263314, -0.85129412])

In [7]:
np.add(A,B)

array([-1.41347051, -0.23647972,  0.98592128, -1.32756218, -1.1658973 ,
       -0.11248538, -1.1076483 ,  3.91589313, -2.74292023, -0.81061849])

In [8]:
# compare values in each index for A and B and list the max value
np.maximum(A,B)

array([-0.32942746,  0.35523941,  1.15249635, -0.46612771, -0.35773992,
       -0.04604959,  0.09227759,  2.27022593, -0.95263314,  0.04067564])

In [9]:
np.minimum(A,B)

array([-1.08404305, -0.59171913, -0.16657507, -0.86143447, -0.80815738,
       -0.06643579, -1.19992588,  1.6456672 , -1.79028709, -0.85129412])

In [11]:
# will open the website below! 

import webbrowser
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'

webbrowser.open(website)

True